config/routes.rb
::Refinery::Application.routes.draw do
  scope(:path => 'sistema-para-locadora-de-veiculos/blog', :module => 'blog') do
    root :to => 'posts#index', :as => 'blog_root'
    match 'feed.rss', :to => 'posts#index', :as => 'blog_rss_feed', :defaults => {:format => "rss"}
    match ':id', :to => 'posts#show', :as => 'blog_post'
    match 'categories/:id', :to => 'categories#show', :as => 'blog_category'
    match ':id/comments', :to => 'posts#comment', :as => 'blog_post_blog_comments'
    get 'archive/:year(/:month)', :to => 'posts#archive', :as => 'archive_blog_posts'
    get 'tagged/:tag_id(/:tag_name)' => 'posts#tagged', :as => 'tagged_posts'
  end

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    scope(:path => 'blog', :as => 'blog', :module => 'blog') do
      root :to => 'posts#index'
      resources :posts do
        collection do
          get :uncategorized
          get :tags
        end
      end

      resources :categories

      resources :comments do
        collection do
          get :approved
          get :rejected
        end
        member do
          get :approved
          get :rejected
        end
      end

      resources :settings do
        collection do
          get :notification_recipients
          post :notification_recipients

          get :moderation
          get :comments
          get :teasers
        end
      end
    end
  end
end

app/models/blog/comment_mailer.rb
require File.expand_path('../../../mailers/blog/comment_mailer', __FILE__)

app/controllers/admin/blog/categories_controller.rb
module Admin
  module Blog
    class CategoriesController < Admin::BaseController

      crudify :blog_category,
              :title_attribute => :title,
              :order => 'title ASC'

    end
  end
end

app/controllers/admin/blog/comments_controller.rb
module Admin
  module Blog
    class CommentsController < Admin::BaseController

      crudify :blog_comment,
              :title_attribute => :name,
              :order => 'published_at DESC'

      def index
        @blog_comments = BlogComment.unmoderated
        render :action => 'index'
      end

      def approved
        unless params[:id].present?
          @blog_comments = BlogComment.approved
          render :action => 'index'
        else
          @blog_comment = BlogComment.find(params[:id])
          @blog_comment.approve!
          flash[:notice] = t('approved', :scope => 'admin.blog.comments', :author => @blog_comment.name)
          redirect_to :action => params[:return_to] || 'index'
        end
      end

      def rejected
        unless params[:id].present?
          @blog_comments = BlogComment.rejected
          render :action => 'index'
        else
          @blog_comment = BlogComment.find(params[:id])
          @blog_comment.reject!
          flash[:notice] = t('rejected', :scope => 'admin.blog.comments', :author => @blog_comment.name)
          redirect_to :action => params[:return_to] || 'index'
        end
      end

    end
  end
end

app/controllers/admin/blog/posts_controller.rb
module Admin
  module Blog
    class PostsController < Admin::BaseController
      require 'will_paginate/array'
      
      crudify :blog_post,
              :title_attribute => :title,
              :order => 'published_at DESC'
          
      def uncategorized
        @blog_posts = BlogPost.uncategorized.paginate({
          :page => params[:page],
          :per_page => BlogPost.per_page
        })
      end
  
      def tags
        op =  case ActiveRecord::Base.connection.adapter_name.downcase
              when 'postgresql'
                '~*'
              else
                'LIKE'
              end
        wildcard =  case ActiveRecord::Base.connection.adapter_name.downcase
                    when 'postgresql'
                      '.*'
                    else
                      '%'
                    end
        @tags = BlogPost.tag_counts_on(:tags).where(
            ["tags.name #{op} ?", "#{wildcard}#{params[:term].to_s.downcase}#{wildcard}"]
          ).map { |tag| {:id => tag.id, :value => tag.name}}
        render :json => @tags.flatten
      end
  
      def create
        # if the position field exists, set this object as last object, given the conditions of this class.
        if BlogPost.column_names.include?("position")
          params[:blog_post].merge!({
            :position => ((BlogPost.maximum(:position, :conditions => "")||-1) + 1)
          })
        end
    
        if BlogPost.column_names.include?("user_id")
          params[:blog_post].merge!({
            :user_id => current_user.id
          })
        end

        if (@blog_post = BlogPost.create(params[:blog_post])).valid?
          (request.xhr? ? flash.now : flash).notice = t(
            'refinery.crudify.created',
            :what => "'#{@blog_post.title}'"
          )

          unless from_dialog?
            unless params[:continue_editing] =~ /true|on|1/
              redirect_back_or_default(admin_blog_posts_url)
            else
              unless request.xhr?
                redirect_to :back
              else
                render :partial => "/shared/message"
              end
            end
          else
            render :text => "<script>parent.window.location = '#{admin_blog_posts_url}';</script>"
          end
        else
          unless request.xhr?
            render :action => 'new'
          else
            render :partial => "/shared/admin/error_messages",
                   :locals => {
                     :object => @blog_post,
                     :include_object_name => true
                   }
          end
        end
      end

      before_filter :find_all_categories,
                    :only => [:new, :edit, :create, :update]

      before_filter :check_category_ids, :only => :update

    protected
      def find_all_categories
        @blog_categories = BlogCategory.find(:all)
      end

      def check_category_ids
        params[:blog_post][:category_ids] ||= []
      end
    end
  end
end

app/controllers/admin/blog/settings_controller.rb
module Admin
  module Blog
    class SettingsController < Admin::BaseController

      def notification_recipients
        @recipients = BlogComment::Notification.recipients

        if request.post?
          BlogComment::Notification.recipients = params[:recipients]
          flash[:notice] = t('updated', :scope => 'admin.blog.settings.notification_recipients',
                             :recipients => BlogComment::Notification.recipients)
          unless request.xhr? or from_dialog?
            redirect_back_or_default(admin_blog_posts_path)
          else
            render :text => "<script type='text/javascript'>parent.window.location = '#{admin_blog_posts_path}';</script>",
                   :layout => false
          end
        end
      end

      def moderation
        enabled = BlogComment::Moderation.toggle!
        unless request.xhr?
          redirect_back_or_default(admin_blog_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end

      def comments
        enabled = BlogComment.toggle!
        unless request.xhr?
          redirect_back_or_default(admin_blog_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end
      
      def teasers
        enabled = BlogPost.teaser_enabled_toggle!
        unless request.xhr?
          redirect_back_or_default(admin_blog_posts_path)
        else
          render :json => {:enabled => enabled},
                 :layout => false
        end
      end

    end
  end
end

app/controllers/blog/categories_controller.rb
module Blog
  class CategoriesController < BlogController

    def show
      @category = BlogCategory.find(params[:id])
      @blog_posts = @category.posts.live.includes(:comments, :categories).paginate({
        :page => params[:page],
        :per_page => RefinerySetting.find_or_set(:blog_posts_per_page, 10)
      })
    end

  end
end

app/controllers/blog/posts_controller.rb
module Blog
  class PostsController < BlogController

    before_filter :find_all_blog_posts, :except => [:archive]
    before_filter :find_blog_post, :only => [:show, :comment, :update_nav]
    before_filter :find_tags

    respond_to :html, :js, :rss

    def index
      # Rss feeders are greedy. Let's give them every blog post instead of paginating.
      (@blog_posts = BlogPost.live.includes(:comments, :categories).all) if request.format.rss?
      respond_with (@blog_posts) do |format|
        format.html
        format.rss
      end
    end

    def show
      @blog_comment = BlogComment.new
      @canonical = url_for(:locale => ::Refinery::I18n.default_frontend_locale) if canonical?
      
      respond_with (@blog_post) do |format|
        format.html { present(@blog_post) }
        format.js { render :partial => 'post', :layout => false }
      end
    end

    def comment
      if (@blog_comment = @blog_post.comments.create(params[:blog_comment])).valid?
        if BlogComment::Moderation.enabled? or @blog_comment.ham?
          begin
            Blog::CommentMailer.notification(@blog_comment, request).deliver
          rescue
            logger.warn "There was an error delivering a blog comment notification.\n#{$!}\n"
          end
        end

        if BlogComment::Moderation.enabled?
          flash[:notice] = t('thank_you_moderated', :scope => 'blog.posts.comments')
          redirect_to blog_post_url(params[:id])
        else
          flash[:notice] = t('thank_you', :scope => 'blog.posts.comments')
          redirect_to blog_post_url(params[:id],
                                    :anchor => "comment-#{@blog_comment.to_param}")
        end
      else
        render :action => 'show'
      end
    end

    def archive
      if params[:month].present?
        date = "#{params[:month]}/#{params[:year]}"
        @archive_date = Time.parse(date)
        @date_title = @archive_date.strftime('%B %Y')
        @blog_posts = BlogPost.live.by_archive(@archive_date).paginate({
          :page => params[:page],
          :per_page => RefinerySetting.find_or_set(:blog_posts_per_page, 10)
        })
      else
        date = "01/#{params[:year]}"
        @archive_date = Time.parse(date)
        @date_title = @archive_date.strftime('%Y')
        @blog_posts = BlogPost.live.by_year(@archive_date).paginate({
          :page => params[:page],
          :per_page => RefinerySetting.find_or_set(:blog_posts_per_page, 10)
        })
      end
      respond_with (@blog_posts)
    end

    def tagged
      @tag = ActsAsTaggableOn::Tag.find(params[:tag_id])
      @tag_name = @tag.name
      @blog_posts = BlogPost.tagged_with(@tag_name).paginate({
        :page => params[:page],
        :per_page => RefinerySetting.find_or_set(:blog_posts_per_page, 10)
      })
    end

  protected

    def find_blog_post
      unless (@blog_post = BlogPost.find(params[:id])).try(:live?)
        if refinery_user? and current_user.authorized_plugins.include?("refinerycms_blog")
          @blog_post = BlogPost.find(params[:id])
        else
          error_404
        end
      end
    end

    def find_all_blog_posts
      @blog_posts = BlogPost.live.includes(:comments, :categories).paginate({
        :page => params[:page],
        :per_page => RefinerySetting.find_or_set(:blog_posts_per_page, 10)
      })
    end

    def find_tags
      @tags = BlogPost.tag_counts_on(:tags)
    end
    
    def canonical?
      ::Refinery.i18n_enabled? && ::Refinery::I18n.default_frontend_locale != ::Refinery::I18n.current_frontend_locale
    end
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController

  helper :blog_posts
  before_filter :find_page, :find_all_blog_categories

protected

  def find_page
    @page = Page.find_by_link_url("/blog")
  end

  def find_all_blog_categories
    @blog_categories = BlogCategory.all
  end

end

app/views/admin/blog/_submenu.html.erb
<nav id='actions' class='multilist'>
  <ul class='search_list'>
    <li class='not_a_link'>
      <%= render :partial => "/shared/admin/search",
                 :locals => {
                   :url => admin_blog_posts_url
                 } %>
    </li>
  </ul>

  <ul class='collapsible_menu'>
    <li class='not_a_link'>
      <%= link_to t('.posts.title'), '#',
                   :class => 'page_copy_icon' %>
    </li>
    <li>
      <%= link_to t('.posts.manage'), admin_blog_posts_path,
                   :class => 'page_icon' %>
    </li>
    <li>
      <%= link_to t('.posts.uncategorized'), uncategorized_admin_blog_posts_url,
                  :class => 'page_icon' %>
    </li>
    <li>
       <%= link_to t('.posts.new'), new_admin_blog_post_url,
                   :class => 'page_add_icon' %>
    </li>
  </ul>
  <% if BlogPost.comments_allowed? %>
    <ul class='collapsible_menu'>
      <li class='not_a_link'>
        <% if BlogComment.unmoderated.any? %>
          <% title = t('.comments.title_with_count', :new_count => BlogComment.unmoderated.size) %>
        <% else %>
          <% title = t('.comments.title') %>
        <% end %>
        <%= link_to title, '#',
                    :class => 'comments_icon' %>
      </li>
      <li>
        <%= link_to t('.comments.new'), admin_blog_comments_path,
                    :class => 'comment_icon' %>
      </li>
      <li>
        <%= link_to t('.comments.approved'), approved_admin_blog_comments_path,
                    :class => 'comment_tick_icon' %>
      </li>
      <li>
        <%= link_to t('.comments.rejected'), rejected_admin_blog_comments_path,
                    :class => 'comment_cross_icon' %>
      </li>
    </ul>
  <% end %>

  <ul class='collapsible_menu'>
    <li class='not_a_link'>
      <%= link_to t('.categories.title'), '#',
                  :class => 'folder_icon' %>
    </li>
    <li>
      <%= link_to t('.categories.manage'), admin_blog_categories_url,
                  :class => 'folder_edit_icon' %>
    </li>
    <li>
      <%= link_to t('.categories.new'), new_admin_blog_category_url(:dialog => true, :height => 325),
                  :class => 'folder_add_icon' %>
    </li>
  </ul>

  <ul class='collapsible_menu'>
    <li class='not_a_link'>
      <%= link_to t('.settings.title'), admin_blog_settings_path,
                  :class => 'settings_icon' %>
    </li>
    <li>
      <%= link_to t('.settings.comments'), comments_admin_blog_settings_url,
                  :class => "#{BlogPost.comments_allowed? ? 'success' : 'failure'}_icon" %>
    </li>
    <li>
      <%= link_to t('.settings.moderation'), moderation_admin_blog_settings_url,
                  :class => "#{BlogComment::Moderation.enabled? ? 'success' : 'failure'}_icon" %>
    </li>
    <li>
      <%= link_to t('.settings.update_notified'),
                  notification_recipients_admin_blog_settings_url(:dialog => true, :height => 400),
                  :class => 'user_comment_icon' %>
    </li>
    <li>
      <%= link_to t('.settings.teasers'),
                  teasers_admin_blog_settings_url, :class => "#{BlogPost.teasers_enabled? ? 'success' : 'failure'}_icon" %>
    </li>
  </ul>

</nav>

<% content_for :stylesheets, stylesheet_link_tag('refinery/refinerycms-blog')%>